version: 2
updates:
# Keep everything on the main branch up-to-date.
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /docker
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
# Receive minor and patch updates on latest release branch.
# Ignore minor releases for NPM since they may ship breaking
# changes, and we don't have the test coverage in place to
# detect that in CI.
- package-ecosystem: npm
  target-branch: 4.13.x
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
- package-ecosystem: docker
  target-branch: 4.13.x
  directory: /docker
  schedule:
    interval: daily
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
