version: 2
updates:
- package-ecosystem: npm
  target-branch: 4.14.x
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
- package-ecosystem: docker
  target-branch: 4.14.x
  directory: /docker
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
- package-ecosystem: github-actions
  target-branch: 4.14.x
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 7
