version: "3"

volumes:
  dependency-track-data:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:snapshot
    ports:
      - "8081:8080"
    volumes:
      - "dependency-track-data:/data"
    restart: unless-stopped

  dtrack-frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: dependencytrack/frontend:snapshot
    depends_on:
      - dtrack-apiserver
    environment:
      - "API_BASE_URL=http://localhost:8081"
      # - "OIDC_ISSUER="
      # - "OIDC_CLIENT_ID="
      # - "OIDC_SCOPE="
      # - "OIDC_FLOW="
    # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "8080:80"
    restart: unless-stopped

