name: i18n
on:
  push:
    branches:
      - 'master' # Default branch
      - 'feature-**' # Feature branches
  pull_request:
    branches:
      - 'master' # Default branch
      - 'feature-**' # Feature branches

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2

      - name: Set up NodeJs
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # tag=v6.3.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Check for Translations
        run: |
          mv src/assets/scss/vendors/chart.js src/assets/scss/vendors/chart.js.skip
          npm run vue-i18n-extract
        continue-on-error: false
