name: Lint
on:
  push:
    branches:
      - 'main' # Default branch
      - 'feature-**' # Feature branches
  pull_request:
    branches:
      - 'main' # Default branch
      - 'feature-**' # Feature branches

permissions: {}

jobs:
  lint-js:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag=v6.0.3
        with:
          persist-credentials: false
      - name: Set up NodeJs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # tag=v6.4.0
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint Prettier
        run: npm run prettier
        continue-on-error: false
      - name: Lint ESLint
        run: npm run eslint
        continue-on-error: true

  lint-i18n:
    name: Lint i18n
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag=v6.0.3
        with:
          persist-credentials: false
      - name: Set up NodeJs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # tag=v6.4.0
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Check for Translations
        run: npm run vue-i18n-extract
        continue-on-error: false
